### ISSUE TITLE
PBat Live is Not Recognizing My Subscription

### ISSUE THREAD

**Issue by 2plyr** [Turqmelon/PBat-Live#1]
(Twitch is 2PLYR) I have subscribed but the website is not recognizing my subscription or giving the extra coin per time watched.
![capture](https://cloud.githubusercontent.com/assets/14254115/14227139/ad261f8a-f8bb-11e5-8ef2-678935ddf1ed.JPG)

**Comment by Turqmelon** [comment]
I'm not able to recreate this issue. Contact twitch support.
