### ISSUE TITLE
Subcribe streak not correct/

### ISSUE THREAD

**Issue by Zentigerr** [Turqmelon/PBat-Live#2]
![chrome_2016-05-13_14-19-27](https://cloud.githubusercontent.com/assets/19351437/15257762/e071b8fc-1915-11e6-91dc-1b89d4b66d73.png)
It says 4 months but i am currently subbed for 8 month streak. I heard it could be becasue i changed payment method at one point.

**Comment by Turqmelon** [comment]
This has been addressed many times by PBat himself.

The sub length is based off the start date Twitch provides us. This is not a bug with our site, you'll need to contact Twitch.
